<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ApricotFramework.IdGeneration.AspNetCore/ApricotFramework.IdGeneration.AspNetCore.csproj" />
  </ItemGroup>

</Project>
